/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ImageBoundingBoxRenderer: typeof import('./src/components/app/growth/ImageBoundingBoxRenderer.vue')['default']
    ImageUploadCard: typeof import('./src/components/app/growth/ImageUploadCard.vue')['default']
    ParticleDot: typeof import('./src/components/ParticleDot.vue')['default']
    ReadingCard: typeof import('./src/components/app/home/ReadingCard.vue')['default']
    ReadingChart: typeof import('./src/components/app/monitor/ReadingChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./src/components/auth/SignInForm.vue')['default']
    ThresholdCard: typeof import('./src/components/admin/thresholds/ThresholdCard.vue')['default']
    ThresholdCreateForm: typeof import('./src/components/admin/thresholds/ThresholdCreateForm.vue')['default']
    ThresholdUpdateForm: typeof import('./src/components/admin/thresholds/ThresholdUpdateForm.vue')['default']
    ToastQueue: typeof import('./src/components/ToastQueue.vue')['default']
    UserCreateForm: typeof import('./src/components/admin/accounts/UserCreateForm.vue')['default']
    UserDeleteForm: typeof import('./src/components/admin/accounts/UserDeleteForm.vue')['default']
    UserUpdateForm: typeof import('./src/components/admin/accounts/UserUpdateForm.vue')['default']
    VideoBoundingBoxRenderer: typeof import('./src/components/app/growth/VideoBoundingBoxRenderer.vue')['default']
    VideoScanCard: typeof import('./src/components/app/growth/VideoScanCard.vue')['default']
  }
}
