/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ImageBoundingBoxRenderer: typeof import('./src/components/app/growth/ImageBoundingBoxRenderer.vue')['default']
    ReadingCard: typeof import('./src/components/app/home/ReadingCard.vue')['default']
    ReadingChart: typeof import('./src/components/app/monitor/ReadingChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./src/components/auth/SignInForm.vue')['default']
    SignUpForm: typeof import('./src/components/auth/SignUpForm.vue')['default']
    ToastQueue: typeof import('./src/components/ToastQueue.vue')['default']
    VideoBoundingBoxRenderer: typeof import('./src/components/app/growth/VideoBoundingBoxRenderer.vue')['default']
  }
}
